### ISSUE TITLE
ERROR: Internal error encountered.

### ISSUE THREAD

**Issue by code-bross** [eventOneHQ/apkup#34]
It seems that an error occurred while editing in the console.
`'google.play.publishingapi.v3.EditsService.Commit`' failed.
How about change the`'--release-notes'` argument optional?

**Comment by nprail** [comment]
Can't tell much from that 🙂

Try again but first run:
```bash
export DEBUG=apkup:*
```
Then paste the full output here. Make sure you redact any sensitive info, though.

Also, what Node version are you on?

**Comment by code-bross** [comment]
edit content

**Comment by nprail** [comment]
I really can't tell much from the info you've provided. Please provide the full output with `DEBUG` enabled. 

Out of curiosity, why do you think that making `release-notes` optional would help? Unfortunately, I don't think I can do that because I think it is required by Google's API. But I'd have to double-check on that.

**Comment by nprail** [comment]
@code-bross Are you still experiencing this issue?
