### ISSUE TITLE
Upload multiple APKs at once

### ISSUE THREAD

**Issue by ryanagler** [eventOneHQ/apkup#6]
Google started rejecting uploads of just 32 bit apk's (they also require 64).  Is there a way to upload both a 32 and 64 apk's at the same time so Google will accept it?

**Comment by nprail** [comment]
@ryanagler This should be relatively easy to implement. In theory, it should just be a matter of changing the `--apk` CLI option to an array. 

If you are using the JS SDK rather than the CLI, you should be able to pass an array of paths for the APK param. Could you please try that and see if it works as expected? If that works correctly, I'll switch the `--apk` option to an array. 

Example:
```javascript
apkup
  .upload(['/path/to/apk32', '/path/to/apk64'], {
    releaseNotes: [
      {
        language: 'en-US',
        text: 'Minor bug fixes...'
      }
    ]
  })
  .then(data => {
    console.log(` > ${data.packageName} version ${data.versionCode} is up!`);
  });
```

**Comment by ryanagler** [comment]
I tried doing it as an array with Node and Google did appear to accept the upload if it had both 32 and 64!  Please update for the CLI, that is what I normally use.

**Comment by nprail** [comment]
@ryanagler I've updated the CLI. Since I don't have a good test case, would you mind testing it? 

You should be able to download and set up the branch like so:
```shell
# download
git clone git@github.com:eventOneHQ/apkup -b 6-multiple-apks
cd apkup

# install/build
npm i
npm run build

# test
node dist/cli/index --key ./auth.json --apk /path/to/apk32 --apk /path/to/apk64
```
